def line():
    A=float(input("ingrese el coeficiente A: "))
    B=float(input("ingrese el coeficiente B: "))
    X1=float(input("ingrese el coeficiente X1: "))
    X2=float(input("ingrese el coeficiente X2: "))
    print(f"el coeficiente A de su ecuacion es: {A}")
    print(f"el coeficiente B de su ecuacion es: {B}")
    print(f"el coeficiente X1 de su ecuacion es: {X1}")
    print(f"el coeficiente X2 de su ecuacion es: {X2}")
    print()
    Y1=(A*X1-B)
    Y2=(A*X2-B)
    print("para la siguiente ecuacion: ")
    print(f"    Y={A}X+{B}")
    print() 
    print("dados los siguientes puntos: ")
    print(f"    P1 ({X1},{Y1})")
    print(f"    P2 ({X2},{Y2})")
    print()
    print(f"la distancia entre ellos es: {((X2-X1)**2+(Y2-Y1)**2)**0.5}")

line()
